apiVersion: v1
kind: ConfigMap
metadata:
  name: "docker-daemon-configmap-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data:
  daemon.json: |-
    {{ include "manager.daemonconfig" . }}
