apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "hydro-serving-manager-rb-{{ .Release.Name }}"
  labels:
    app: {{ include "manager.name" . }}
    chart: {{ include "manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}"hydro-serving-manager-sa-{{ .Release.Name }}"{{ end }}

