apiVersion: v1
kind: Service
metadata:
  name: "postgres-{{ .Release.Name }}"
  labels:
    app: {{ include "postgres.name" . }}
    chart: {{ include "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: {{ include "postgres.name" . }}
    release: {{ .Release.Name }}
