apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "influx.fullname" . }}
  labels:
    app: {{ include "influx.name" . }}
    chart: {{ include "influx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "influx.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "influx.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
        {{- if .Values.global.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.global.persistence.existingClaim }}{{ .Values.global.persistence.existingClaim }}{{- else }}"serving-{{ .Release.Name }}"{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
